### PR TITLE
A shortcut for game move by best point from analysis.

### PR DESCRIPTION
**Pull request by k-l-lambda**
I tried to use analyzer & AI player simultaneously, that's buggy when I back off and re-move frequently. So use an analyzer as an AI player is more practicable at present. And you can also control the pondering time flexibly.

I chose *Space* key as the shortcut for *move-by-analysis*, that's can be discussed.

### CODE REVIEW

**Comment by yishn** [comment]
Not sure why this is necessary? We have "Generate Move" which will let the engine choose the move for you.

**Comment by k-l-lambda** [comment]
As I said, AI player synchronization is buggy and troublesome when changing game tree position frequently.

It's useful for me. Never mind.

**Comment by yishn** [comment]
Would be nice if you could create an issue on how it is buggy with detailed reproduction steps and visualization.

**Comment by k-l-lambda** [comment]
Try to keep turning mouse wheel when AI player is thinking.

It seems caused by synchronous GTP player communication. Meanwhile, the AI analyser is more flexible.

**Pull request closed without merging**
