### PR TITLE
Add the option to switch on/off the display of variations

### PR DESCRIPTION
**Pull request by ebifrier**
This enables to switch on/off the variasions display started by mouse over.
It corresponds to the last comment in #649 .

### CODE REVIEW

**Comment by yishn** [comment]
I think what @SKHD wanted was the ability hide the heatmap completely. I don't see any reason why we would disable playing out variations on mouse over. Just don't mouse over if you don't want to see the variation played out.

**Comment by ebifrier** [comment]
What you say is theoretically correct. However, it is difficult for a careless person like me to always be careful not to hover over. I'm sure that this option is useful for careless people.

**Comment by yishn** [comment]
Then I would prefer to merge this option into the Preferences drawer along with 'Instantly play out analysis variations on board'. We can have a select box instead with the options 'Don't Play', 'Instantly', and 'Move by Move' or something like that.

**Comment by ebifrier** [comment]
Ok. That's a nice idea! I'll try to fix it.

**Comment by SHKD13** [comment]
@yishn Not exactly. I don't wanna see any candidate moves on board during the game mode, just a clean board + winrate graph in a top right corner like it was in v0.43.
I see no reason to display candidate moves on board in any mode except special analysis mode F4.

**Comment by yishn** [comment]
@SHKD13 Correct me if I'm wrong, but it sounds like you want to hide the heat map. Win rate data should only be recorded if you're in analysis mode anyway, otherwise there will be no analysis.

**Comment by SHKD13** [comment]
@yishn Yes, would be nice to have an option to disable the heat map with candidate moves during the game mode.
Otherwise this is impossible to play with engine by yourself when it shows you all the best moves

**Comment by ebifrier** [comment]
I added the new variable 'board.variation_replay_mode' to the setting, and removed   'board.variation_instant_replay'. Please review it.

Also, I set the title of the preference item to 'Replay mode of analysis variations:', it may be a bit weird. Please let me know if there is an alternative.

**Comment by ebifrier** [comment]
Thank you for your reply! Thanks a lot!

**Pull request merged**
