### PR TITLE
fix #498

### LINKED ISSUE #498: Hang on engine 'pass'
The analysis parsing for the engine hangs the engine when the last move is a 'pass' in pv -- so you have to detach/reattach the engine. This results in data in the chain having a null value when executing .map causing an Error.

The analysis parsing doesn't seem to handle pass at all, so it also seems any variation with a 'pass' in it will result in an erroneous variation (specifically, the current regex will pick up moves after the last pass). All the variations are x,y integer coords so I don't even know if/how pass is handled to fix it.

Temporarily to stop Sabaki from hanging with the engine I have filtered out pvs that are null in App.js:
`.filter(pv => pv != null)`
`.filter(({move}) => move.match(/^[A-Za-z]\d+$/))`

### PR DESCRIPTION
**Pull request by dbosst**
Fix engine hangs by making sure data isn't null in analysis parsing.
Fixes the engine hang problem in #498 ( when 'pass' is last in the pv for the engine)

Fixes #498

### CODE REVIEW

**Comment by yishn** [comment]
Are you sure this will fix anything? Because in the previous `.map` right before your `.filter` we return the following:

~~~js
return keys.reduce((acc, x, i) => (acc[x] = values[i], acc), {})
~~~

which will never be `null`, maybe only `{}`.

**Comment by yishn** [comment]
Please submit your fix for #499 in another pull request.

**Comment by dbosst** [comment]
Hmm I guess that wasn't exactly the source of the bug, I'm sure the fact pass is in the move list is part of the problem, so it seems my last patch resolves the issue. I created a test sgf to attach the engine to hopefully verify this fixes it (Attach with -r 0 -p -v 160: it should generate move 435 as pass and end the game so scoring should show up next -- without the patch it hangs indefinitely)

[hopeless.sgf.zip](https://github.com/SabakiHQ/Sabaki/files/2718669/hopeless.sgf.zip)

For reference the original error you get is:

App.js?afc7:2172 Uncaught TypeError: Cannot read property 'map' of undefined
    at line.split.slice.map.map.filter.map.map.filter.map (App.js?afc7:2172)
    at Array.map (<anonymous>)
    at subscribe (App.js?afc7:2167)
    at subscriber (stream-controller.js?2fc0:86)
    at EventEmitter._responseLineEmitter.on (stream-controller.js?2fc0:63)
    at EventEmitter.emit (events.js:182)
    at StreamController.output.line (stream-controller.js?2fc0:19)
    at Socket.readable.on.data (helper.js?cb5e:13)
    at Socket.emit (events.js:182)
    at addChunk (_stream_readable.js:279)

**Comment by yishn** [comment]
I can't reproduce it using the latest versions (Sabaki v0.41.0/Leela Zero v0.16). Leela Zero resigns and Sabaki handles it peacefully. Analysis doesn't hang either.

You say PV ending in `pass` are the problem, but [in this line](https://github.com/SabakiHQ/Sabaki/blob/master/src/components/App.js#L2147) we're not matching `pass` at all, so they get discarded early on already.

According to the original error, the problem is that the variable `pv` in [line 2172](https://github.com/SabakiHQ/Sabaki/blob/master/src/components/App.js#L2172) is `null`. But analyzing the `map` and `filter` chain, you can conclude that that is impossible.

**Comment by dbosst** [comment]
So yours advances to move 435? Can you post the last part of your GTP console? Here you can see where mine hang (It never gets the actual pass move processed as move 435)

○ PZ-V160> lz-genmove_analyze B 100
connection failed
Thinking at most 2678400.0 seconds...
NN eval=0.999905
Playouts: 9, Win: 99.94%, PV: pass T3 S3
Playouts: 22, Win: 99.94%, PV: pass T3 S3 M8 pass T17
Playouts: 34, Win: 99.94%, PV: pass T3 S3 M8 pass T17 S17 Q19 B1
Playouts: 46, Win: 99.94%, PV: pass T3 S3 M8 pass T17 S17 Q19 B1 M14 T3 M12
Playouts: 62, Win: 99.94%, PV: pass T3 S3 M8 pass T17 S17 Q19 B1 M14 T3 M12 B19
Playouts: 74, Win: 99.94%, PV: pass T3 S3 M8 pass T17 S17 Q19 B1 M14 T3 M12 B19
Playouts: 86, Win: 99.94%, PV: pass T3 S3 M8 pass T17 S17 Q19 B1 M14 T3 M12 B19
Playouts: 97, Win: 99.94%, PV: pass T3 S3 M8 pass T17 S17 Q19 B1 M14 T3 M12 B19
Playouts: 106, Win: 99.94%, PV: pass T3 S3 M8 pass T17 S17 Q19 B1 M14 T3 M12 B19
Playouts: 119, Win: 99.94%, PV: pass T3 S3 M8 pass T17 S17 Q19 B1 M14 T3 M12 B19
Playouts: 131, Win: 99.94%, PV: pass T3 S3 M8 pass T17 S17 Q19 B1 M14 T3 M12 B19
Playouts: 142, Win: 99.94%, PV: pass T3 S3 M8 pass T17 S17 Q19 B1 M14 T3 M12 B19
2678364.5s left, stopping early.
pass ->      34 (V: 99.93%) (N:  2.09%) PV: pass T3 S3 M8 pass T17 S17 Q19 B1 M14 T3 M12 B19
  T3 ->      18 (V: 99.94%) (N:  0.98%) PV: T3 M8 pass M12 S3 H8 B1 H12 A3 A17 B17 D19 E19
 S19 ->      17 (V: 99.93%) (N:  1.00%) PV: S19 M14 pass T3 S3 H8 pass M8 T3 H6 B19 T17 S17
 T17 ->      17 (V: 99.93%) (N:  0.96%) PV: T17 P1 Q1 H8 pass T3 S3 A3 B3 M8 A3 H12 S19
 D19 ->      16 (V: 99.94%) (N:  0.95%) PV: D19 T3 S3 H8 pass M8 B19 M12 S1 H12 Q19 M14 B1
 E19 ->      15 (V: 99.93%) (N:  0.94%) PV: E19 M8 pass H8 B19 T3 S3 M6 T3 T5 T6 Q1 T5
  S1 ->      15 (V: 99.93%) (N:  0.94%) PV: S1 Q1 P1 M8 pass T3 S3 M12 B19 H12 T5 M14 S19
 N19 ->       9 (V: 99.93%) (N:  0.94%) PV: N19 T17 S17 M8 pass T3 S3 H12 S19
 B19 ->       8 (V: 99.93%) (N:  0.92%) PV: B19 F9 pass A3 B3 M8 A3 T17
7.1 average depth, 14 max depth
132 non leaf nodes, 1.13 average children
150 visits, 20129 nodes, 149 playouts, 4 n/s

**Pull request closed without merging**
