### PR TITLE
Implement "Flip Board"

### LINKED ISSUE #534: Flip board (reflection)
Enhancement to be added to the Tools menu. Along with the ability to rotate the board in 2 dimensions (**Tools/Rotate Clockwise** & **Tools/Rotate Anticlockwise**) it would be useful to be able to flip the board (equivalent to reflecting the board or rotating it through 3 dimensions):
(1) **Horizontally**  (for example, around column K on the 19x19 goban) so that the left edge column (column A) is swapped with the right edge column (eg 19x19 goban column T), etc;
(2) **Vertically** (for example, around row 10 on the 19x19 goban) so that the top row (eg 19x19 goban row 19) is swapped with the bottom row (row 1).
I suggest that the new commands be named **Flip up** and **Flip right**.

### PR DESCRIPTION
**Pull request by fohristiwhirl**
There's a certain amount of "repeating yourself" in this patch but it works...

Fixes #534

### CODE REVIEW

**Comment by yishn** [comment]
Looks good to me! 👍 Thanks!

**Comment by fohristiwhirl** [comment]
@yishn - actually, would you like a cleanup of this code? I've reduced its length and redundancy a little bit. Shall I submit a new PR? It's not super important.

**Comment by GopherAl** [comment]
@fohristiwhirl - (Sorry, I don't know any other way of attempting to message you). Would you possibly be interested in taking on what I think would be a fairly simple project in SabakiHQ/Shudan: issue **Alternative board coordinates #4**  ? (It will be very difficult for me to progress this on my own since my current (rusty) skills are creating macros in Lotus 1-2-3 and a little scripting in Excel. So I face a very steep learning curve to achieve something fairly simple.) Any help would be much appreciated!!!
.

**Comment by GopherAl** [comment]
@yishn @fohristiwhirl It would be very handy to have keyboard shortcuts for **Flip Board** and **Rotate Clockwise** & **Rotate Anticlockwise**. I hope you deem this desirable and are able to add these shortcuts. (Many thanks to both of you for this and your other vast contributions!)

**Comment by yishn** [comment]
@fohristiwhirl Sure, go ahead. @GopherAI Actually, I don't think board transformations are that important. Do you use them that often? Why?

**Comment by GopherAl** [comment]
@yishn I have been doing a lot of study of AlphaZero and pro games and have made frequent use of the Rotate transformations when comparing positions in different games. The Flip Board transformation extends that capability. Transformations aid searches for similarities and differences between positions in different games.

**Comment by yishn** [comment]
I see, in that case maybe rewriting the whole SGF isn't your intention at all. You just need a quick, temporary transformation tool. Now I wonder if anyone needs such an invasive transformation tool like we have now, but I digress... 

Right now we're short on available shortcut keys; do you have any suggestions?

**Comment by GopherAl** [comment]
@yishn my apologies for not making it clear; I envisaged **Flip Board** to be for only temporary changes of viewpoint for purposes of analysis.  
Regarding **keyboard shortcuts**, the most important one is for rotation, since that is the command that is likely to be repeated the most to reach the desired position. I suggest _CTRL+R_ or _ALT+R_ for **Rotate Clockwise** (or adding _SHIFT_ as well if preferred). _ALT+Right_ for **Flip Right** and _ALT+Up_ for **Flip Up** are intuitive shortcuts for the Flip Board commands. If these shortcuts are unavailable for any reason, please offer some guidance on what keys and combinations would be okay.

**Pull request merged**
