### PR TITLE
Rotation functions

### PR DESCRIPTION
**Pull request by fohristiwhirl**
Rotation functions

### CODE REVIEW

**Comment by fohristiwhirl** [comment]
Meanwhile, an extremely naive method for the App component looks like this:

```javascript
    rotateClockwise() {

        const rotation = require('../modules/rotation')
        
        let root = gametree.getRoot(this.state.treePosition[0])
        let trees = gametree.getTreesRecursive(root)

        for (let tree of trees) {
            for (let node of tree.nodes) {
                rotation.rotateNodeClockwise(node, 19)      // FIXME - get actual size; check if height == width
                node.board = null
            }
        }
    }
```

This does basically work.

**Comment by fohristiwhirl** [comment]
Should I add my (naive) method and menu item to the PR?

**Comment by fohristiwhirl** [comment]
So I suggest we simply disallow rotation while engines are attached. I'm not sure how to check for that though.

**Comment by yishn** [comment]
Will it be a problem if engines are attached? Theoretically, the board state will be synced via `enginesyncer`, the worst case being the whole game being replayed to the engine.

**Comment by yishn** [comment]
I can tell you that it won't be a problem theoretically, so we don't have to disallow rotation when engines are attached. But I need to test it, of course.

**Comment by fohristiwhirl** [comment]
I tested it with a random move generator which makes legal moves or passes when there aren't any - everything worked as expected.

**Comment by fohristiwhirl** [comment]
OK I got around to implementing anticlockwise properly.

**Comment by yishn** [comment]
Thank you, that's much more than you promised!

**Pull request merged**
